language: c
branches:
    only:
        - master
matrix:
    include:
        - os: linux
          compiler: gcc
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -Bbuild
script:
  - cd build
  - make -j 2
after_success:
  - echo "Everything is ok"
after_failure:
  - echo "Something gone wrong"

notifications:
    email:
        recipients:
            - adembudak@outlook.com
        on_success: always
        on_failure: never

