language: c
branches: 
   only:
       - travisIntegration
compiler: gcc

before_script:
  - mkdir build && cd build
  - cmake ..
script:
  - make -j 2
after_success:
  - echo "Everything is ok"
after_failure:
  - echo "Something gone wrong"
